services:
  orderservice-db:
    image: postgres:17.2
    container_name: orderservice-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ORDERSERVICE_DB_NAME}
      POSTGRES_USER: ${ORDERSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ORDERSERVICE_DB_PASSWORD}
    ports:
      - "${ORDERSERVICE_DB_PORT}:5432"
    volumes:
      - orderservice-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: slds-keycloak
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  orderservice-db-data:
  keycloak-data:
