services:
  orderservice-db:
    image: postgres:17.2
    container_name: orderservice-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ORDERSERVICE_DB_NAME}
      POSTGRES_USER: ${ORDERSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ORDERSERVICE_DB_PASSWORD}
    ports:
      - "${ORDERSERVICE_DB_PORT}:5432"
    volumes:
      - orderservice-db-data:/var/lib/postgresql/data

  deliveryservice-db:
    image: postgres:17.2
    container_name: deliveryservice-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: deliveryservice_db
      POSTGRES_USER: deliveryservice_user
      POSTGRES_PASSWORD: passer
    ports:
      - "5436:5432"
    volumes:
      - deliveryservice-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: slds-keycloak
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: slds-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  api-gateway:
    build:
      context: ./src
      dockerfile: Gateway/ApiGateway/Dockerfile
    container_name: slds-api-gateway
    restart: unless-stopped
    ports:
      - "5000:8080"
    depends_on:
      - orderservice-db

volumes:
  orderservice-db-data:
  deliveryservice-db-data:
  keycloak-data:
  rabbitmq-data:
